### ISSUE TITLE
OnTouch Button animation

### ISSUE THREAD

**Issue by vitaminncpp** [vitaminncpp/TouchDroid#34]
There is already animation for onCLick Listener, but it is not working for OnTouch Listener.

**Comment by SKR301** [comment]
Why did you assign this to me, without consulting first :laughing: 
I'll look into it

**Comment by Akshayaap** [comment]
- I just need a custom animation which will trigger by calling `view.animate(anim);` function.

**Comment by Akshayaap** [comment]
- I think this is not necessary

**Comment by vitaminncpp** [comment]
@SKR301 you haven't done it yet, neither did I 😆.

**Comment by SKR301** [comment]
![image](https://github.com/vitaminncpp/TouchDroid/assets/47807051/86ef9649-735f-469b-9dba-7abead67ec97)
You mentioned it as not necessary. Closing it.
